repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.5.7"
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        exclude: "tests/integration/test_roles/conftest|examples/with_roles|docs/usage/1-database-models"
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        exclude: docs
  - repo: https://github.com/python-formate/flake8-dunder-all
    rev: v0.4.1
    hooks:
      - id: ensure-dunder-all
        exclude: "test*|examples*|tools"
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.19.0
    hooks:
      - id: slotscheck
        exclude: "test_*|docs|examples"
        entry: env PYTHONPATH=litestar_users slotscheck
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args:
          [
            --disable=MD013,
            --disable=MD033,
            --disable=MD046,
            --disable=MD050,
            --disable=MD052,
            --disable=MD012,
            --disable=MD036,
            --disable=MD034,
            --disable=MD038,
          ]
  - repo: https://github.com/johnfraney/flake8-markdown
    rev: v0.5.0
    hooks:
      - id: flake8-markdown
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.1"
    hooks:
      - id: mypy
        exclude: "test_apps"
        additional_dependencies:
          [
            advanced_alchemy,
            asyncpg,
            litestar,
            passlib,
            pytest,
            python-jose,
            sqlalchemy,
            types-click,
            uvicorn,
          ]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.375
    hooks:
      - id: pyright
        exclude: "test_apps|tools"
        additional_dependencies:
          [
            advanced_alchemy,
            asyncpg,
            litestar,
            passlib,
            pytest,
            python-jose,
            pyyaml,
            sqlalchemy,
            types-click,
            uvicorn,
          ]
