repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.291"
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        exclude: |
          tests/integration/test_roles/conftest
          examples/with_roles
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        exclude: docs
  - repo: https://github.com/python-formate/flake8-dunder-all
    rev: v0.3.0
    hooks:
      - id: ensure-dunder-all
        exclude: "test*|examples*|tools"
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args:
          [
            --disable=MD013,
            --disable=MD033,
            --disable=MD046,
            --disable=MD050,
            --disable=MD052,
            --disable=MD012,
            --disable=MD036,
            --disable=MD034,
            --disable=MD038,
          ]
  - repo: https://github.com/johnfraney/flake8-markdown
    rev: v0.5.0
    hooks:
      - id: flake8-markdown
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.5.1"
    hooks:
      - id: mypy
        exclude: "test_apps"
        additional_dependencies:
          [
            advanced_alchemy,
            asyncpg,
            passlib,
            pytest,
            python-jose,
            litestar,
            sqlalchemy,
            uvicorn,
          ]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.328
    hooks:
      - id: pyright
        exclude: "test_apps|tools"
        additional_dependencies:
          [
            advanced_alchemy,
            asyncpg,
            passlib,
            pytest,
            python-jose,
            pyyaml,
            litestar,
            sqlalchemy,
            uvicorn,
          ]
