name: publish
on:
  release:
    types: [published]
jobs:
  publish-release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "0.5.14"
      - name: Install dependencies
        run: uv sync
      - name: publish
        shell: bash
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_TOKEN }}
